---
abstract: 'Run git commands on multiple repos at once.'
author:
  - 'Henry Van Styn <vanstyn@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-eachgit
requires:
  Path::Class: 0.33
  strict: 0
  warnings: 0
resources:
  repository: https://github.com/vanstyn/App-eachgit.git
version: 0.3
